# force run: 1
dist: xenial
language: c
compiler:
  - clang
  - gcc
python:
  - "3.6"
sudo: required
before_install:
    - sudo -H PATH="${PATH}:/usr/local/clang-3.4/bin" pip install -r requirements.txt
    - sudo -H DEBIAN_FRONTEND=noninteractive apt-get update
    - pip install --user cpp-coveralls
env:
  global:
    - COVERALLS_PARALLEL=true
script:
    sh -x ./scripts/do-test.sh
after_success:
  - if [ "${CC}" = "gcc" ];
    then
      coveralls --gcov gcov --gcov-options '\-lp';
    fi
