language: c
compiler:
  - clang
  - gcc
python:
  - "2.7"
sudo: required
before_install:
    - sudo pip install -r requirements.txt
    - sudo DEBIAN_FRONTEND=noninteractive apt-get update
script:
    sh -x ./scripts/do-test.sh
